ci: enhance sync-template workflow

diff --git a/.github/workflows/sync-template-non-workflow.yml b/.github/workflows/sync-template-non-workflow.yml
--- a/.github/workflows/sync-template-non-workflow.yml
+++ b/.github/workflows/sync-template-non-workflow.yml
@@ -1,10 +1,10 @@
 ---
-name: Sync boilerplate files (test)
+name: Sync boilerplate files (non-workflow)
 
 on:
   schedule:
     - cron: '0 9 * * 1' # Every Monday at 9am
-  workflow_dispatch: # Manual trigger
+  workflow_dispatch:
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -39,9 +39,32 @@ jobs:
                 - scripts/update-unreleased.sh
           github-token: ${{ secrets.GITHUB_TOKEN }}
           fail-on-error: 'true'
+      - name: Exit if no changes
+        if: steps.sync.outputs.has-changes == 'false'
+        run: |
+          echo '::notice::No changes detected. Exiting.'
+          exit 0
+      - name: Stage changes
+        run: |
+          set -e
+          git add .
+          if git diff --cached --quiet; then
+            echo '::error::Sync action reported changes, but no files were staged. ' \
+                 'This may indicate gitignore conflicts or other issues.'
+            exit 1
+          fi
+          echo '::notice::Changes staged. Proceeding with commit.'
+      - name: Commit changes
+        uses: iarekylew00t/verified-bot-commit@v2
+        with:
+          auto-stage: false
+          if-no-commit: error
+          update-local: false
+          message: 'chore: auto-sync boilerplate files'
+          files: |
+            **
       - name: Build PR body
         id: pr-body
-        if: steps.sync.outputs.has-changes == 'true'
         uses: actions/github-script@v7
         with:
           result-encoding: string
@@ -80,13 +103,6 @@ jobs:
             }
 
             return body;
-      # - name: Commit changes
-      #   if: steps.autoupdate-pre-commit.outputs.has_updates == 'true'
-      #   uses: iarekylew00t/verified-bot-commit@v2
-      #   with:
-      #     message: 'chore(pre-commit): bump hook versions'
-      #     files: |
-      #       ${{ env.PRECOMMIT_CONFIG_FILE }}
       - name: Create pull request
         uses: peter-evans/create-pull-request@v8
         with:
@@ -96,5 +112,5 @@ jobs:
           title: 'chore: auto-sync boilerplate files'
           body: ${{ steps.pr-body.outputs.result }}
           labels: |
-            boilerplate
             automated
+            boilerplate
